export const dashboard = [
  {
    id: "00000001",
    title: "other",
    panelInView: true,
    panels: [
      {
        id: 1,
        title: "Request",
        gridPos: {
          h: 7,
          w: 12,
          x: 0,
          y: 1,
        },
        type: "graph",
        tooltip: {
          show: false,
        },
        xaxis: {
          mode: "time",
        },
        yaxis: {},
      },
    ],
  },
  {
    id: "00000002",
    title: "sample",
    panelInView: true,
    panels: [
      {
        id: 1,
        title: 1,
        gridPos: {
          w: 2,
          h: 4,
          x: 0,
          y: 0,
          i: "1",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 2,
        title: 2,
        gridPos: {
          w: 2,
          h: 4,
          x: 2,
          y: 0,
          i: "2",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 3,
        title: 3,
        gridPos: {
          w: 2,
          h: 4,
          x: 4,
          y: 0,
          i: "3",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 4,
        title: 4,
        gridPos: {
          w: 2,
          h: 4,
          x: 6,
          y: 0,
          i: "4",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 5,
        title: 5,
        gridPos: {
          w: 2,
          h: 4,
          x: 8,
          y: 0,
          i: "5",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 6,
        title: 6,
        gridPos: {
          w: 2,
          h: 4,
          x: 10,
          y: 0,
          i: "6",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 7,
        title: 7,
        gridPos: {
          w: 6,
          h: 5,
          x: 0,
          y: 4,
          i: "7",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "list",
      },
      {
        id: 8,
        title: 8,
        gridPos: {
          w: 6,
          h: 5,
          x: 6,
          y: 4,
          i: "7",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "logs",
      },
      {
        id: 9,
        title: 9,
        gridPos: {
          w: 12,
          h: 5,
          x: 0,
          y: 9,
          i: "9",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
      {
        id: 10,
        title: 10,
        gridPos: {
          w: 12,
          h: 5,
          x: 0,
          y: 14,
          i: "10",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
    ],
  },
];
