import { handleSeries } from "../../app/plugins/elastic.handler";
import { vegaLitePieSpec, vegaLiteSeriseSpec } from "./dashboardVegaLiteSpec";

import bodySent from "../../assets/jsons/bodysent.json";
import statusCode from "../../assets/jsons/statuscode.json";
import uv from "../../assets/jsons/uv.json";
import top5 from "../../assets/jsons/uv.json";
import session from "../../assets/jsons/session.json";
import browser from "../../assets/jsons/browser.json";
import {
  vegaErrorBand,
  vegaGeo,
  vegaHitmap,
  vegaThreshold,
} from "../graphs/VegaChartPage/spec";

export const dashboard = [
  {
    id: "00000006",
    title: "telco",
    label: "vega",
    panelInView: true,
    isResizable: false,
    isDraggable: false,
    panels: [
      {
        id: 1,
        title: "request",
        gridPos: {
          w: 6,
          h: 3,
          x: 0,
          y: 0,
        },
        url: "request",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "short",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 2,
        title: "traffic",
        gridPos: {
          w: 6,
          h: 3,
          x: 6,
          y: 0,
        },
        url: "traffic",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 3,
        title: "session",
        gridPos: {
          w: 6,
          h: 3,
          x: 0,
          y: 3,
        },
        url: "session",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "short",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 4,
        title: "uv",
        gridPos: {
          w: 6,
          h: 3,
          x: 6,
          y: 3,
        },
        url: "uv",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "short",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 5,
        title: "request",
        gridPos: {
          w: 3,
          h: 3,
          x: 0,
          y: 6,
        },
        url: "requestTotal",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "none",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 6,
        title: "Body Sent Traffic",
        gridPos: {
          w: 3,
          h: 3,
          x: 3,
          y: 6,
        },
        url: "bodysenttraffic",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 7,
        title: "Body Sent",
        gridPos: {
          w: 12,
          h: 4,
          x: 0,
          y: 9,
        },
        url: "bodysent",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
          },
          y: {
            field: "value",
            type: "quantitative",
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 8,
        title: "Status Code",
        gridPos: {
          w: 9,
          h: 4,
          x: 0,
          y: 12,
        },
        url: "statuscode",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
          },
          y: {
            field: "value",
            type: "quantitative",
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 9,
        title: "Status Code(count)",
        gridPos: {
          w: 3,
          h: 4,
          x: 9,
          y: 12,
        },
        url: "statuscodeCount",
        estype: "telco",
        type: "graph",
        fieldConfig: {},
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          donut: false,
        },
        kinds: "pie",
      },
      {
        id: 10,
        title: "Request Hit Ratio",
        gridPos: {
          w: 9,
          h: 4,
          x: 0,
          y: 15,
        },
        url: "requesthitratio",
        estype: "telco",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
          },
          y: {
            field: "value",
            type: "quantitative",
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 11,
        title: "Request Hit Ratio(count)",
        gridPos: {
          w: 3,
          h: 4,
          x: 9,
          y: 15,
        },
        url: "requesthitratioCount",
        estype: "telco",
        type: "graph",
        fieldConfig: {},
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          donut: false,
        },
        kinds: "pie",
      },
    ],
  },
  {
    id: "00000005",
    title: "service",
    label: "vega",
    panelInView: true,
    isResizable: false,
    isDraggable: false,
    panels: [
      {
        id: 1,
        title: "bodysenttraffic",
        gridPos: {
          w: 3,
          h: 3,
          x: 6,
          y: 3,
        },
        url: "bodysenttraffic",

        estype: "real",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 2,
        title: "referer",
        gridPos: {
          w: 7,
          h: 5,
          x: 0,
          y: 16,
        },
        url: "referer",

        estype: "real",
        type: "graph",
        fieldConfig: {},
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: true,
          },
          donut: true,
        },
        kinds: "pie",
      },
      {
        id: 3,
        title: "bodysent",
        gridPos: {
          w: 8,
          h: 5,
          x: 0,
          y: 6,
        },
        url: "bodysent",

        estype: "real",
        type: "graph",
        fieldConfig: {},
        vega: {
          x: {
            field: "date",
            type: "temporal",
          },
          y: {
            field: "value",
            type: "quantitative",
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: ["brush"],
        },
        kinds: "line",
      },
      {
        id: 4,
        title: "status code",
        gridPos: {
          w: 8,
          h: 5,
          x: 0,
          y: 11,
        },
        url: "statuscode",

        estype: "real",
        type: "graph",
        fieldConfig: {},
        vega: {
          x: {
            field: "date",
            type: "temporal",
          },
          y: {
            field: "value",
            type: "quantitative",
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: ["brush"],
        },
        kinds: "line",
      },
      {
        id: 6,
        title: "os",
        gridPos: {
          w: 3,
          h: 5,
          x: 0,
          y: 21,
        },
        url: "os",
        estype: "real",
        type: "graph",
        fieldConfig: {},
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          donut: true,
        },
        kinds: "pie",
      },
      {
        id: 7,
        title: "device",
        gridPos: {
          w: 3,
          h: 5,
          x: 3,
          y: 21,
        },
        url: "device",

        estype: "real",
        type: "graph",
        fieldConfig: {},
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: true,
          },
          donut: true,
        },
        kinds: "pie",
      },
      {
        id: 8,
        title: "requests",
        gridPos: {
          w: 3,
          h: 3,
          x: 0,
          y: 3,
        },
        url: "requests",

        estype: "real",
        type: "graph",
        fieldConfig: {
          unit: "none",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: [],
        },
        kinds: "line",
      },
      {
        id: 9,
        title: "statuscodecount",
        gridPos: {
          w: 4,
          h: 5,
          x: 8,
          y: 6,
        },
        url: "statuscodecount",

        estype: "real",
        type: "graph",
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: true,
          },
          donut: false,
        },
        kinds: "pie",
      },
      {
        id: 10,
        title: "hitratiocount",
        gridPos: {
          w: 4,
          h: 5,
          x: 8,
          y: 11,
        },
        url: "hitratiocount",

        estype: "real",
        type: "graph",
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: true,
          },
          donut: false,
        },
        kinds: "pie",
      },
      {
        id: 11,
        title: "request",
        gridPos: {
          w: 6,
          h: 3,
          x: 0,
          y: 0,
        },
        url: "request",

        estype: "real",
        type: "graph",
        fieldConfig: {
          unit: "short",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: ["brush"],
        },
        kinds: "line",
      },
      {
        id: 12,
        title: "traffic",
        gridPos: {
          w: 6,
          h: 3,
          x: 6,
          y: 0,
        },
        url: "traffic",

        estype: "real",
        type: "graph",
        fieldConfig: {
          unit: "bytes",
        },
        vega: {
          x: {
            field: "date",
            type: "temporal",
            axis: null,
          },
          y: {
            field: "value",
            type: "quantitative",
            axis: null,
          },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: null,
          },
          params: ["brush"],
        },
        kinds: "line",
      },
      {
        id: 13,
        title: "browser",
        gridPos: {
          w: 3,
          h: 5,
          x: 6,
          y: 21,
        },
        url: "browser",

        estype: "real",
        type: "graph",
        vega: {
          theta: { field: "value", type: "quantitative" },
          color: {
            field: "symbol",
            type: "nominal",
            scale: { scheme: "category20" },
            legend: true,
          },
          donut: false,
        },
        kinds: "pie",
      },
    ],
  },
  {
    id: "00000004",
    title: "requesttest",
    label: "vega",
    panelInView: true,
    isResizable: false,
    isDraggable: false,
    panels: [
      {
        id: 1,
        title: "request top 5",
        gridPos: {
          w: 6,
          h: 5,
          x: 0,
          y: 0,
        },
        url: "top5",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "line",
      },
      {
        id: 2,
        title: "body sent",
        gridPos: {
          w: 6,
          h: 5,
          x: 6,
          y: 0,
        },
        url: "requests",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "line",
      },
      {
        id: 3,
        title: "status Code",
        gridPos: {
          w: 12,
          h: 5,
          x: 0,
          y: 11,
        },
        url: "bodysent",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "line",
      },
      {
        id: 4,
        title: "bodysenttraffic",
        gridPos: {
          w: 5,
          h: 4,
          x: 5,
          y: 5,
        },
        url: "bodysenttraffic",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "line",
      },
      {
        id: 5,
        title: "uv",
        gridPos: {
          h: 6,
          w: 6,
          x: 6,
          y: 15,
        },
        url: "uv",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "line",
      },
      {
        id: 6,
        title: "session",
        gridPos: {
          h: 6,
          w: 6,
          x: 0,
          y: 15,
        },
        url: "session",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "line",
      },
      {
        id: 7,
        title: "referer",
        gridPos: {
          w: 7,
          h: 6,
          x: 0,
          y: 21,
        },
        url: "referer",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "pie",
      },
      {
        id: 8,
        title: "os",
        gridPos: {
          w: 3,
          h: 6,
          x: 0,
          y: 27,
        },
        url: "os",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "pie",
      },
      {
        id: 9,
        title: "browser",
        gridPos: {
          w: 3,
          h: 6,
          x: 3,
          y: 27,
        },
        url: "browser",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "pie",
      },
      {
        id: 10,
        title: "device",
        gridPos: {
          w: 3,
          h: 6,
          x: 6,
          y: 27,
        },
        url: "device",
        type: "graph",
        opt: {
          legend: null,
        },
        kinds: "pie",
      },
    ],
  },
  {
    id: "00000001",
    title: "chartjs",
    label: "chartjs",
    panelInView: true,
    isResizable: false,
    isDraggable: false,
    panels: [
      {
        id: 1,
        title: "status Code",
        gridPos: {
          h: 5,
          w: 4,
          x: 0,
          y: 0,
        },
      },
      {
        id: 2,
        title: "status Code",
        gridPos: {
          h: 5,
          w: 4,
          x: 4,
          y: 0,
        },
      },
      {
        id: 3,
        title: "status Code",
        gridPos: {
          h: 7,
          w: 12,
          x: 0,
          y: 5,
        },
      },
    ],
  },
  {
    id: "00000002",
    title: "vega-lite",
    label: "vega",
    panelInView: true,
    isResizable: false,
    isDraggable: false,
    panels: [
      {
        id: 21,
        title: 21,
        gridPos: {
          w: 6,
          h: 5,
          x: 0,
          y: 1,
          i: "1",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaThreshold,
        data: handleSeries(browser.responses[0].aggregations),
      },
      {
        id: 22,
        title: 22,
        gridPos: {
          w: 6,
          h: 5,
          x: 6,
          y: 1,
          i: "1",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaGeo,
        data: handleSeries(browser.responses[0].aggregations),
      },
      {
        id: 11,
        title: 1,
        gridPos: {
          w: 2,
          h: 3,
          x: 0,
          y: 1,
          i: "1",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaErrorBand,
        data: handleSeries(browser.responses[0].aggregations),
      },
      {
        id: 12,
        title: 1,
        gridPos: {
          w: 2,
          h: 3,
          x: 2,
          y: 0,
          i: "1",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaLitePieSpec,
        data: handleSeries(browser.responses[0].aggregations),
      },
      {
        id: 1,
        title: 1,
        gridPos: {
          w: 2,
          h: 3,
          x: 4,
          y: 0,
          i: "1",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaLitePieSpec,
        data: handleSeries(browser.responses[0].aggregations),
      },
      // {
      //   id: 2,
      //   title: 2,
      //   gridPos: {
      //     w: 2,
      //     h: 4,
      //     x: 2,
      //     y: 0,
      //     i: "2",
      //     minW: 2,
      //     minH: 3,
      //     moved: false,
      //     static: false,
      //   },
      //   type: "graph",
      // },
      // {
      //   id: 3,
      //   title: 3,
      //   gridPos: {
      //     w: 2,
      //     h: 4,
      //     x: 4,
      //     y: 0,
      //     i: "3",
      //     minW: 2,
      //     minH: 3,
      //     moved: false,
      //     static: false,
      //   },
      //   type: "graph",
      // },
      {
        id: 4,
        title: 4,
        gridPos: {
          w: 6,
          h: 3,
          x: 6,
          y: 0,
          i: "4",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaLiteSeriseSpec,
        data: handleSeries(uv.responses[0].aggregations),
      },
      // {
      //   id: 5,
      //   title: 5,
      //   gridPos: {
      //     w: 2,
      //     h: 4,
      //     x: 8,
      //     y: 0,
      //     i: "5",
      //     minW: 2,
      //     minH: 3,
      //     moved: false,
      //     static: false,
      //   },
      //   type: "graph",
      // },
      // {
      //   id: 6,
      //   title: 6,
      //   gridPos: {
      //     w: 2,
      //     h: 4,
      //     x: 10,
      //     y: 0,
      //     i: "6",
      //     minW: 2,
      //     minH: 3,
      //     moved: false,
      //     static: false,
      //   },
      //   type: "graph",
      // },
      {
        id: 7,
        title: 7,
        gridPos: {
          w: 6,
          h: 5,
          x: 0,
          y: 3,
          i: "7",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "list",
      },
      {
        id: 8,
        title: 8,
        gridPos: {
          w: 6,
          h: 5,
          x: 6,
          y: 3,
          i: "7",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaHitmap,
        data: handleSeries(session.responses[0].aggregations),
      },
      {
        id: 9,
        title: 9,
        gridPos: {
          w: 12,
          h: 5,
          x: 0,
          y: 0,
          i: "9",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaLiteSeriseSpec,
        data: handleSeries(bodySent.responses[1].aggregations),
      },
      {
        id: 10,
        title: 10,
        gridPos: {
          w: 12,
          h: 5,
          x: 0,
          y: 13,
          i: "10",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
        spec: vegaLiteSeriseSpec,
        data: handleSeries(statusCode.responses[0].aggregations),
      },
    ],
  },
  {
    id: "00000003",
    title: "chartjs",
    panelInView: true,
    label: "highchart",
    isResizable: false,
    isDraggable: false,
    panels: [
      {
        id: 1,
        title: 1,
        gridPos: {
          w: 12,
          h: 5,
          x: 0,
          y: 13,
          i: "10",
          minW: 2,
          minH: 3,
          moved: false,
          static: false,
        },
        type: "graph",
      },
    ],
  },
];
